server {
    listen 80;
    server_name mangos-api.ima-wiseutils.com;

    access_log /var/log/nginx/mangos/access-api.log;
    error_log /var/log/nginx/mangos/error-api.log;

    root /home/imanol/projects/wiseutils/pay-trackr/server/api;
    index index.php;

    # Block internal files
    location = /config.php { deny all; }

    # Front controller
    location / {
        try_files $uri /index.php?$query_string;
    }

    location = /index.php {
        include fastcgi_params;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        fastcgi_read_timeout 180s;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ \.php$ {
        deny all;
    }
}
