CREATE TABLE payments (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    user_id VARCHAR(36) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(500) DEFAULT '',
    amount DECIMAL(12,2) NOT NULL,
    category_id VARCHAR(36),
    is_paid TINYINT(1) NOT NULL DEFAULT 0,
    paid_ts TIMESTAMP NULL DEFAULT NULL,
    recurrent_id VARCHAR(36),
    payment_type ENUM('one-time', 'recurrent') NOT NULL DEFAULT 'one-time',
    due_ts TIMESTAMP NULL DEFAULT NULL,
    source ENUM('manual', 'whatsapp-text', 'whatsapp-audio', 'whatsapp-image', 'whatsapp-pdf') NOT NULL DEFAULT 'manual',
    status ENUM('pending', 'reviewed') NOT NULL DEFAULT 'reviewed',
    needs_revision TINYINT(1) NOT NULL DEFAULT 0,
    is_whatsapp TINYINT(1) NOT NULL DEFAULT 0,
    audio_transcription TEXT,
    created_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES expense_categories(id) ON DELETE SET NULL,
    FOREIGN KEY (recurrent_id) REFERENCES recurrents(id) ON DELETE SET NULL,
    INDEX idx_user_type_due (user_id, payment_type, due_ts),
    INDEX idx_user_created (user_id, created_ts),
    INDEX idx_recurrent (recurrent_id)
);
