<?php
/**
 * Dumps the current fx_rate table into a SQL migration file so the historical
 * series ships in the repo and runs automatically on deploy via migrate.php.
 *
 * Usage: php server/scripts/generate-fx-seed-migration.php
 *
 * Output: server/migrations/{date}_NNN_seed_fx_rate_history.sql
 *
 * Idempotent at deploy time: the INSERT uses ON DUPLICATE KEY UPDATE so
 * re-running on a populated DB just overwrites with the same values.
 *
 * One-shot: this is meant to be regenerated only when the historical data
 * needs a snapshot refresh (e.g., before a fresh prod deploy). For ongoing
 * updates, use server/scripts/backfill-fx-history.php on a cron.
 */

$config = require __DIR__ . '/../config.php';
$db = $config['db'];

$pdo = new PDO(
    "mysql:host={$db['host']};dbname={$db['name']};charset=utf8mb4",
    $db['user'],
    $db['pass'],
    [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
);

$rows = $pdo->query(
    "SELECT currency_code, `date`, rate_to_ars, source
     FROM fx_rate ORDER BY currency_code, `date`"
)->fetchAll(PDO::FETCH_ASSOC);

if (empty($rows)) {
    fwrite(STDERR, "fx_rate is empty — nothing to seed. Run backfill first.\n");
    exit(1);
}

// Pick the next migration number (date + sequence).
$migrations_dir = __DIR__ . '/../migrations';
$existing = glob($migrations_dir . '/*.sql');
$max_seq = 0;
foreach ($existing as $f) {
    if (preg_match('/_(\d{3})_/', basename($f), $m)) {
        $max_seq = max($max_seq, (int)$m[1]);
    }
}
$next_seq = str_pad($max_seq + 1, 3, '0', STR_PAD_LEFT);
$today = date('Ymd');
$filename = "{$today}_{$next_seq}_seed_fx_rate_history.sql";
$path = $migrations_dir . '/' . $filename;

// Build the SQL. Multi-row INSERT in chunks to stay well under
// max_allowed_packet (default 64MB on MySQL 8) — 500 rows per statement is
// safely small and still vastly faster than per-row inserts.
$header = <<<SQL
-- Seed historical USD blue rates from argentinadatos.com.
-- Generated by server/scripts/generate-fx-seed-migration.php on {$today}.
--
-- Daily series since 2011, used by the analytics YoY widget for USD-anchor
-- normalization. Idempotent: ON DUPLICATE KEY UPDATE keeps the operation
-- safe to re-run, and the daily refresh cron (backfill-fx-history.php)
-- continues from here onward.

SQL;

$lines = [$header];
$row_count = count($rows);
$chunk_size = 500;

for ($i = 0; $i < $row_count; $i += $chunk_size) {
    $chunk = array_slice($rows, $i, $chunk_size);
    $values = [];
    foreach ($chunk as $r) {
        $cur  = $pdo->quote($r['currency_code']);
        $date = $pdo->quote($r['date']);
        $rate = (float)$r['rate_to_ars'];
        $src  = $pdo->quote($r['source']);
        $values[] = "($cur, $date, $rate, $src)";
    }
    $lines[] =
        "INSERT INTO fx_rate (currency_code, `date`, rate_to_ars, source) VALUES\n" .
        implode(",\n", $values) . "\n" .
        "ON DUPLICATE KEY UPDATE rate_to_ars = VALUES(rate_to_ars), source = VALUES(source);";
}

file_put_contents($path, implode("\n\n", $lines) . "\n");

$size_kb = round(filesize($path) / 1024, 1);
echo "Wrote {$path}\n";
echo "  {$row_count} rows, {$size_kb} KB\n";
